name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and publish
      uses: helaili/jekyll-action@2.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
