name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Jekyll site
      uses: helaili/jekyll-action@2.0.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Directory where Jekyll builds the site
